# all source codes is based on python2
# https://m.blog.naver.com/sogangori/220701662749
all:
	#g++ call_func.c -I/usr/include/python3.8 -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8
	gcc -o main main.cpp -I/usr/include/python3.8 -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8
	./main
	#./lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
	gcc -o main2 main2.cpp -I/usr/include/python3.8 -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8
	./main2

