all:
	#g++ call_func.c -I/usr/include/python3.8 -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8
	gcc call_func.c -I/usr/include/python3.8 -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8
	./a.out
	#./lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so

